AWSTemplateFormatVersion: 2010-09-09
Description: Enable config
Resources:
  ConfigBucket:
    Type: AWS::S3::Bucket
  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'config-role-${AWS::Region}'
      ManagedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSConfigRole']
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub 'config-policy-${AWS::Region}'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketAcl
                Resource: !Sub 'arn:aws:s3:::${ConfigBucket}'
              - Effect: Allow
                Action:
                  - s3:PutObject*
                Resource: !Sub 'arn:aws:s3:::${ConfigBucket}/AWSLogs/${AWS::AccountId}/*'
                Condition:
                  StringEquals:
                    s3:x-amz-acl: bucket-owner-full-control
  ConfigConfigurationRecorder: 
    Type: AWS::Config::ConfigurationRecorder
    Properties: 
      Name: default
      RecordingGroup: 
        AllSupported: true
        IncludeGlobalResourceTypes: true
      RoleARN: !GetAtt [ConfigRole, Arn]
  ConfigDeliveryChannel: 
    Type: AWS::Config::DeliveryChannel
    Properties:
      Name: default
      S3BucketName: !Ref ConfigBucket