AWSTemplateFormatVersion: 2010-09-09
Description: S3 Encryption Compliance Check
Parameters:
  ConfigRuleName:
    Type: String
    Default: s3encryptioncompliancecheck
    Description: The name that you assign to the AWS Config rule
    MinLength: 1
    ConstraintDescription: This parameter is required
  ConfigRuleDescription:
    Type: String
    Default: A rule that determines whether checked resources are configured with encryption
    Description: A description about this AWS Config rule
    MinLength: 1
    ConstraintDescription: This parameter is required
  S3Bucket:
    Description: The name of the Amazon S3 bucket where the .zip file that contains your Amazon Config Rule is stored. This bucket must reside in the same AWS Region from where this CloudFormation template is executed
    MaxLength: 63
    MinLength: 1
    Type: String
    ConstraintDescription: This parameter is required
  S3Key:
    Type: String
    Default: configrule.zip
    Description: The location and name of the .zip file within the Amazon S3 bucket that contains your Amazon Config Rule
    MinLength: 1
    ConstraintDescription: This parameter is required
Resources:
  ConfigPermissionToCallLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
          - EncryptionAtRestComplianceCheck
          - Arn
      Action: lambda:InvokeFunction
      Principal: config.amazonaws.com
  ConfigRuleForEncryptionAtRest:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigPermissionToCallLambda
    Properties:
      ConfigRuleName: !Ref ConfigRuleName
      Description: !Ref ConfigRuleDescription
      Scope:
        ComplianceResourceTypes:
          - AWS::S3::Bucket
      Source:
        Owner: "CUSTOM_LAMBDA"
        SourceDetails:
          -
            EventSource: "aws.config"
            MessageType: "ConfigurationItemChangeNotification"
        SourceIdentifier:
          Fn::GetAtt:
            - EncryptionAtRestComplianceCheck
            - Arn
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'lambda-execution-role-${AWS::Region}-${ConfigRuleName}'
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - s3:GetEncryptionConfiguration
                Resource: '*'
            Version: 2012-10-17
          PolicyName: !Sub 'lambda-execution-policy-${AWS::Region}-${ConfigRuleName}'
  EncryptionAtRestComplianceCheck:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref ConfigRuleName
      Handler: configrule.configrule
      Runtime: python2.7
      Timeout: 30
      Role:
        Fn::GetAtt:
          - "LambdaExecutionRole"
          - "Arn"
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key